### ISSUE TITLE
Can bypass everything by

### ISSUE THREAD

**Issue by derDere** [AlexNisnevich/untrusted#427] opened 2019-06-07 12:48 UTC
Hi,
using this method I'm able to always bypass every validation check and just placing what I need:

```
    var old = map['vali' + 'dateExactlyXManyObjects'];

    map['vali' + 'dateExactlyXManyObjects'] = (i,o) => {
    	if (o === 'exit') return old(2,o)
    	return old(i,o);
    };
    
    map.placeObject(20,8,'exit');
```

**Comment by pppery** [comment] 2019-07-18 00:11
This is a duplicate of #316, which was confirmed as intentional (this trick only works in bonus levels)

**Closed** 2019-07-24 07:42 UTC
